config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: :logout

  resources :workspaces, only: [:index, :new, :create, :destroy, :show] do
    resources :lists, only: [:create, :destroy] do
      resources :items, only: [:create, :destroy, :update]
    end
  end

  root to: "workspaces#index"
end

app/models/workspace.rb
# frozen_string_literal: true

class Workspace < ApplicationRecord
  has_many :lists, -> { order(id: :asc) }, inverse_of: :workspace, dependent: :destroy

  validates :name, :public_id, presence: true, length: {maximum: 255}

  before_validation :assign_uniq_id, unless: :public_id

  def to_param() = public_id

  private

  def assign_uniq_id
    self.public_id = Nanoid.generate(size: 6)
  end
end

app/controllers/workspaces_controller.rb
# frozen_string_literal: true

class WorkspacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def new
    workspace = Workspace.new
    render locals: {workspace: workspace}
  end

  def create
    workspace = Workspace.new(workspace_params)
    if workspace.save
      # populate demo data
      Workspaces::CreateDemo.call(**{workspace})
      redirect_to workspace_path(workspace), notice: "Welcome to your new workspace!"
    else
      flash.now[:alert] = "Failed to create a workspace: #{workspace.errors.full_messages.join(";")}"
      render :new, locals: {workspace}
    end
  end

  def index
  end

  def show
    workspace = Workspace.find_by!(public_id: params[:id])
    render locals: {workspace}
  end

  private

  def workspace_params
    params.require(:workspace).permit(:name)
  end
end

app/views/workspaces/index.html.erb
<div class="any-panel-wide">
  <div class="mb-4">
    <div class="any-banner" role="alert" data-controller="banner" data-banner-id="welcome">
      <svg data-action="click->banner#close" class="any-banner--btn" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path class="heroicon-ui" d="M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2zm0 2v14h14V5H5zm8.41 7l1.42 1.41a1 1 0 1 1-1.42 1.42L12 13.4l-1.41 1.42a1 1 0 1 1-1.42-1.42L10.6 12l-1.42-1.41a1 1 0 1 1 1.42-1.42L12 10.6l1.41-1.42a1 1 0 1 1 1.42 1.42L13.4 12z"/></svg>
      <p class="font-bold">Welcome to AnyCable demo app—AnyWork!</p>
      <p>AnyWork allows you to create <em>workspaces</em> containing one or many TODO lists and, of course,
      a chat (because no real-time framework demo could exist without chats 😉).</p>
      <p>All changes within a workspace are propagated to all the open pages (aka connected clients), so everyone stays in sync.</p>
    </div>
  </div>
  <div id="choose">
    <h2 class="mb-2">Choose workspace</h2>
    <div class="flex items-center">
      <div>Open </div><%= link_to "Demo", workspace_path(:demo), class: "any-button-outlined ml-2 mr-2 no-underline" %>
      <div>workspace or </div>
      <%= link_to "Create", new_workspace_path, class: "any-button-outlined ml-2 mr-2 no-underline" %>
      <div> a new one!</div>
    </div>
  </div>
  <div id="recent" class="mt-10" data-controller="workspaces--recent">
    <h2 class="mb-2">Recently viewed workspaces</h2>
  </div>
</div>

app/views/workspaces/new.html.erb
<div class="any-panel-wide" id="<%= dom_id(workspace, :new) %>">
  <div>
    <h2 class="mb-2">Create new workspace</h2>
    <%= form_for workspace, html: {class: "flex items-center border-b border-b-2 border-red mb-4 pb-1", data: {controller: "forms--remote"}} do |f| %>
      <%= f.text_field :name, class: "any-text-input", placeholder: "Enter name", autocomplete: "off" %>
      <%= f.button "Create", type: :submit, class: "flex-shrink-0 any-button" %>
    <% end %>
  </div>
</div>

app/views/workspaces/show.html.erb
<div class="px-6" data-controller="workspaces--remember" data-workspaces--remember-url="<%= workspace_path(workspace) %>" data-workspaces--remember-name="<%= workspace.name %>">
  <div class="grid grid-cols-1 lg:grid-cols-chat gap-4" data-controller="workspace" data-workspace-id="<%= workspace.to_param %>">
    <%= render "chats/chat", workspace: workspace %>
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-4" id="<%= dom_id(workspace, :lists) %>" data-target="workspace.lists">
      <div class="any-banner mb-4" role="alert" data-controller="banner" data-banner-id="todo">
        <svg data-action="click->banner#close" class="any-banner--btn" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path class="heroicon-ui" d="M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2zm0 2v14h14V5H5zm8.41 7l1.42 1.41a1 1 0 1 1-1.42 1.42L12 13.4l-1.41 1.42a1 1 0 1 1-1.42-1.42L10.6 12l-1.42-1.41a1 1 0 1 1 1.42-1.42L12 10.6l1.41-1.42a1 1 0 1 1 1.42 1.42L13.4 12z"/></svg>
        <p class="font-bold">TODOs with live updates</p>
        <p>
          This part of the app implements a typical TODO application backed by REST API.
          It is spiced with <em>cables</em> to synchronize updates between the connected clients.
        </p>
        <br/>
        <p>Check out <code>ListsController</code> and <code>ItemsController</code> classes.</p>
      </div>
      <%= render workspace.lists %>
      <%= render "lists/new", workspace: workspace %>
    </div>
  </div>
</div>