config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: :logout

  resources :workspaces, only: [:index, :new, :create, :destroy, :show] do
    resources :lists, only: [:create, :destroy] do
      resources :items, only: [:create, :destroy, :update]
    end
  end

  root to: "workspaces#index"
end

app/views/shared/_alerts.html.erb
<div class="absolute mt-1 w-full">
  <div class="flex justify-center">
    <% if flash[:notice] %>
      <div data-controller="alert" class="max-w-sm bg-white border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md" role="alert">
        <p class="text-sm"><%= flash[:notice] %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div data-controller="alert" class="max-w-sm bg-white border-t-4 border-red rounded-b text-red px-4 py-3 shadow-md" role="alert">
        <p class="text-sm"><%= flash[:alert] %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="flex items-center justify-between flex-wrap p-6" data-controller="nav">
  <div class="flex items-center flex-shrink-0 text-black mr-6">
    <%= link_to root_path do %>
      <svg class="h-16 w-16 mr-2" width="90" height="90" viewBox="0 0 90 90" xmlns="http://www.w3.org/2000/svg"><path d="M78,22.118034 L41,40.618034 L41,87.263932 L78,68.763932 L78,22.118034 Z M76.645898,20.559017 L40,2.23606798 L3.35410197,20.559017 L40,38.881966 L76.645898,20.559017 Z M2,22.118034 L2,68.763932 L39,87.263932 L39,40.618034 L2,22.118034 Z M0,20 L40,0 L80,20 L80,70 L40,90 L0,70 L0,20 Z M23,20 L27,18 L41,25 L37,27 L23,20 Z M37,13 L41,11 L55,18 L51,20 L37,13 Z" id="Rectangle-9" fill="#363636" stroke-width="1" fill-rule="evenodd"></path></svg>
    <% end %>
    <div class="flex flex-col content-start">
      <p class="font-semibold text-xl tracking-tight">AnyWork</p>
      <p class="text-sm tracking-tight text-grey"><a href="https://anycable.io/" target="_blank">AnyCable</a> demo</p>
    </div>
  </div>
  <div class="block lg:hidden">
    <button data-action="nav#toggleMenu" class="flex items-center px-3 py-2 border rounded text-black border-black hover:text-grey hover:border-grey focus:outline-none outline-none">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div data-target="nav.menu" class="w-full hidden lg:visible text-md block flex-grow lg:flex lg:items-center lg:w-auto bg-white lg:bg-transparent shadow-md lg:shadow-none pl-2 lg:pl-0 pb-2 lg:pb-0">
    <div class="lg:flex-grow p-4 lg:p-0">
      <%= link_to "Workspaces", workspaces_path, class: "block mt-4 lg:inline-block lg:mt-0 text-black hover:text-red mr-4 no-underline" %>
    </div>
    <div class="pl-4 flex flex-col lg:flex-row">
      <% if logged_in? %>
        <%= form_tag logout_path, method: :delete do %>
          <span>Welcome, <%= current_user.name %>!</span>
          <span class="text-sm">(<%=
            button_tag "Sign out", type: :submit, class: "text-black hover:text-red no-underline" %>)</span>
        <% end %>
      <% else %>
        <div>
          <%= link_to "Sign in", login_path, class: "text-black hover:text-red mr-4 no-underline" %>
        </div>
      <% end %>
      <label title="Cable connection status" data-controller="connection" for="toogle-connect" class="mt-4 lg:mt-0 ml-0 lg:ml-2 flex items-center cursor-pointer">
        <svg data-target="connection.icon" class="any-toggle--icon active fill-current h-6 w-6 mr-2 text-grey" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path class="heroicon-ui" d="M4.06 13a8 8 0 0 0 5.18 6.51A18.5 18.5 0 0 1 8.02 13H4.06zm0-2h3.96a18.5 18.5 0 0 1 1.22-6.51A8 8 0 0 0 4.06 11zm15.88 0a8 8 0 0 0-5.18-6.51A18.5 18.5 0 0 1 15.98 11h3.96zm0 2h-3.96a18.5 18.5 0 0 1-1.22 6.51A8 8 0 0 0 19.94 13zm-9.92 0c.16 3.95 1.23 7 1.98 7s1.82-3.05 1.98-7h-3.96zm0-2h3.96c-.16-3.95-1.23-7-1.98-7s-1.82 3.05-1.98 7zM12 22a10 10 0 1 1 0-20 10 10 0 0 1 0 20z"/></svg>
        <div class="relative">
          <input data-action="connection#toggleState" data-target="connection.toggle" id="toogle-connect" type="checkbox" class="hidden" checked />
          <div class="any-toggle--line w-10 h-4 bg-gray-400 rounded-full shadow-inner"></div>
          <div class="any-toggle--dot absolute w-6 h-6 bg-grey rounded-full shadow inset-y-0 left-0"></div>
        </div>
      </label>
    </div>
  </div>
</nav>