config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: :logout

  resources :workspaces, only: [:index, :new, :create, :destroy, :show] do
    resources :lists, only: [:create, :destroy] do
      resources :items, only: [:create, :destroy, :update]
    end
  end

  root to: "workspaces#index"
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  validates :desc, presence: true

  belongs_to :list

  scope :completed, -> { where(completed: true) }
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_workspace, :set_list
  before_action :set_item, only: [:destroy, :update]

  after_action :broadcast_new_item, only: [:create]
  after_action :broadcast_changes, only: [:update, :destroy]

  attr_reader :workspace, :list, :item

  def create
    @item = Item.new(item_params)
    item.list = list

    if item.save
      flash[:notice] = "New item has been added to #{list.name}!"
    else
      flash[:alert] = "Failed to create an item: #{item.errors.full_messages.join(";")}"
    end

    redirect_to workspace
  end

  def update
    item.update!(item_params)
    respond_to do |format|
      format.json do
        render json: item.as_json(only: [:id, :desc, :completed])
      end

      format.html do
        flash[:notice] = "Item has been updated"
        redirect_to workspace
      end
    end
  end

  def destroy
    item.destroy!

    respond_to do |format|
      format.json do
        render json: {deletedId: item.id}
      end

      format.html do
        flash[:notice] = "Item has been deleted"
        redirect_to workspace
      end
    end
  end

  private

  def item_params
    params.require(:item).permit(:desc, :completed)
  end

  def set_workspace
    @workspace = Workspace.find_by!(public_id: params[:workspace_id])
  end

  def set_list
    @list = @workspace.lists.find(params[:list_id])
  end

  def set_item
    @item = @list.items.find(params[:id])
  end

  def broadcast_new_item
    return if item.errors.any?
    ListChannel.broadcast_to list, type: "created", html: render_to_string(partial: "items/item", layout: false, locals: {item})
  end

  def broadcast_changes
    return if item.errors.any?
    if item.destroyed?
      ListChannel.broadcast_to list, type: "deleted", id: item.id
    else
      ListChannel.broadcast_to list, type: "updated", id: item.id, desc: item.desc, completed: item.completed
    end
  end
end

app/views/items/_item.html.erb
<div class="flex mb-2 items-center any-list--item <%=  item.completed? ? "checked" : "" %>" id="<%= dom_id(item) %>">
  <label class="any-check mr-4">
    <input data-action="list#toggleCompleted" data-url="<%= workspace_list_item_path(item.list.workspace, item.list, item) %>" type="checkbox" class="hidden" <%= item.completed? ? "checked" : "" %>>
    <svg class="hidden w-4 h-4 text-green-600 pointer-events-none" viewBox="0 0 172 172"><g fill="none" stroke-width="none" stroke-miterlimit="10" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode:normal"><path d="M0 172V0h172v172z"/><path d="M145.433 37.933L64.5 118.8658 33.7337 88.0996l-10.134 10.1341L64.5 139.1341l91.067-91.067z" fill="currentColor" stroke-width="1"/></g></svg>
  </label>
  <p data-controller="linkify" class="any-list--item--text break-words pr-1 w-full text-sm"><%= item.desc %></p>
  <button data-action="list#deleteItem" data-url="<%= workspace_list_item_path(item.list.workspace, item.list, item) %>" class="focus:outline-none outline-none hover:text-red py-2 rounded inline-flex items-center delete-btn">
    <svg class="fill-current w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22 22"><path d="M8 6V4c0-1.1.9-2 2-2h4a2 2 0 0 1 2 2v2h5a1 1 0 0 1 0 2h-1v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V8H3a1 1 0 1 1 0-2h5zM6 8v12h12V8H6zm8-2V4h-4v2h4zm-4 4a1 1 0 0 1 1 1v6a1 1 0 0 1-2 0v-6a1 1 0 0 1 1-1zm4 0a1 1 0 0 1 1 1v6a1 1 0 0 1-2 0v-6a1 1 0 0 1 1-1z"/>
    </svg>
  </button>
</div>